export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_USERS = 'FETCH_USER';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const FETCH_USERS_FAILED = 'FETCH_USER_FAILED';

export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';
export const ADD_PROJECTS_FAILED = 'ADD_PROJECTS_FAILED';
export const SEARCH_PROJECT = 'SEARCH_PROJECT';

export const GET_ASSIGN_USER_PROJECT = 'GET_ASSIGN_USER_PROJECT';
export const GET_ASSIGN_PROJECT_FAILED = 'GET_ASSIGN_PROJECT_FAILED';
export const ADD_ASSIGN_USER_PROJECT = 'ADD_ASSIGN_USER_PROJECT';
export const ADD_ASSIGN_PROJECT_FAILED = 'ADD_ASSIGN_PROJECT_FAILED';
// export const ASSIGN_USER_PROJECT = 'ASSIGN_USER_PROJECT';
// export const ASSIGN_USER_PROJECT_FAILED = 'ASSIGN_USER_PROJECT_FAILED';
export const REMOVE_ASSIGN_USER_PROJECT = 'REMOVE_ASSIGN_USER_PROJECT';
export const REMOVE_ASSIGN_USER_PROJECT_FAILED =
  'REMOVE_ASSIGN_USER_PROJECT_FAILED';

export const ADD_BUG = 'ADD_BUG';
export const ADD_BUG_FAILED = 'ADD_BUG_FAILED';
export const GET_BUGS = 'GET_BUGS';
export const GET_BUGS_FAILED = 'GET_BUGS_FAILED';
export const ASSIGN_BUGS_TO_USER = 'ASSIGN_BUGS_TO_USER';
export const ASSIGN_BUGS_TO_USER_FAILED = 'ASSIGN_BUGS_TO_USER_FAILED';
export const GET_ASSIGN_BUGS_USER = 'GET_ASSIGN_BUGS_USER';
export const UPDATE_BUG = 'UPDATE_BUG';
export const UPDATE_BUG_FAILED = 'UPDATE_BUG_FAILED';
export const DELETE_BUG = 'DELETE_BUG';
export const DELETE_BUG_FAILED = 'DELETE_BUG_FAILED';
export const GET_BUG_IMAGES = 'GET_BUG_IMAGES';
export const GET_BUG_IMAGES_FAILED = 'GET_BUG_IMAGES_FAILED';
export const SEARCH_BUG = 'SEARCH_BUG';
export const SEARCH_BUG_FAILED = 'SEARCH_BUG_FAILED';
